bossBar:
  #默认bossbar的显示时长,ticks为单位,minecraft中 1秒 = 20ticks. 默认为4秒,tick受性能影响 不能保证20tick = 1秒
  timer: 80
  #默认bossbar进度条的颜色，默认绿色(不是文字颜色)可选: GREEN,BLUE,PINK,PURPLE,RED,WHITE,YELLOW
  color: "GREEN"
  #默认bossbar进度条的风格,默认 SOLID , 可选: SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  style: "SOLID"