#数据库相关设置
sql:
  #数据库类型, 可选: MYSQL, SQLITE
  driver: SQLITE
  #MYSQL连接地址:
  host: localhost
  #MYSQL数据库端口
  port: 3306
  #数据库名, 即SQLITE的文件名
  database: database
  #MYSQL用户名
  username: root
  #MYSQL密码
  password: 2636257370
  #玩家数据表名称
  playerTable: CM_PLAYER
  #群组数据表名称
  groupTable: CM_GROUP

#私聊相关设置:
private_message:
  #如果在私聊中, 输入一下文字可快速退出私聊.
  exit_text: "exit"
  #过滤器, 是否要过滤私聊文字.
  filter: true
  #是否允许在私聊中使用颜色代码, 前提是发送方有权限: chatmanagement.player.chatcolor
  color_text: true
  #私聊格式:
  #{player_name} - 玩家名称, {message} - 文本
  format_receive: "&d&l[私聊] &a玩家: &e{sender_name} &a对你说: &2"
  format_send: "&d&l[私聊] &a你对玩家 &e{receiver_name} &a说: &3"
  #私聊文本悬浮文字
  #此处无法使用任何占位符.
  text_holo:
    - "&a点击将该玩家设置为私聊对象~"
  #设置悬浮文字的点击效果.
  #默认执行指令以下指令: {sender_name} - 发送方的ID.
  #功能: 将发送方设置为私聊对象.
  holo_command: "/chatm pm {sender_name}"

#公屏聊天设置
general_message:
  #冷却时间, 玩家聊天间隔必须大于等于这个数, 否则无法发送文字. 以秒为单位
  cooldown: 2.0

#过滤器相关设置
filter:
  #是否在非私聊状态时启用
  enable: true
  #是否过滤私聊中的文字
  enable_pm: true

#bossbar相关设置
bossBar:
  #默认bossbar的显示时长,ticks为单位,minecraft中 1秒 = 20ticks. 默认为4秒,tick受性能影响 不能保证20tick = 1秒
  timer: 80
  #默认bossbar进度条的颜色，默认绿色(不是文字颜色)可选: GREEN,BLUE,PINK,PURPLE,RED,WHITE,YELLOW
  color: "GREEN"
  #默认bossbar进度条的风格,默认 SOLID , 可选: SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  style: "SOLID"