name: ChatManagement
version: '${project.version}'
description: 'A ChatManagement plugin.'
main: me.serliunx.chatmanagement.ChatManagement
api-version: 1.17
authors: [ SerLiunx ]
commands:
  chatmanagement:
    aliases: ["chatm", cm]
    description: main command for ChatManagement.
